### ISSUE TITLE
Manage GCP infra with Crossplane on kind cluster

### ISSUE THREAD

**Issue by olga-mir** [olga-mir/k8s#8]
# Why

To manage GCP infra in declarative IaC way, but not in terraform. Other options considered are Pulumi and KCC (Kubernetes config connector). KCC is Google focused and in future I might expand this approach to AWS.

## Why on kind

I'd love to run management cluster on a real cloud infra like it is done https://github.com/olga-mir/k8s-multi-cluster
The cost of management cluster is minimal for the side-of-desk experiments, but cognitive overload and extra time required for this setup don't worth it currently.

# Steps and requirements

1. Kind config and deploy.sh script in source control, single command spin up.

2. install Crossplane
TODO - version crossplane download
```
helm repo add crossplane-stable https://charts.crossplane.io/stable
helm repo update
helm install crossplane --namespace crossplane-system --create-namespace crossplane-stable/crossplane
kubectl apply -f https://raw.githubusercontent.com/crossplane/provider-gcp/master/package/crossplane.yaml
```

3. Once off GCP setup

In separate folder, call out in the docs as once-off

```
gcloud iam service-accounts create crossplane-gcp-provider --display-name "Crossplane GCP provider account"
gcloud iam service-accounts keys create crossplane-gcp-provider-key.json --iam-account crossplane-gcp-provider@$PROJECT_ID.iam.gserviceaccount.com
gcloud projects add-iam-policy-binding YOUR_PROJECT_ID --member="serviceAccount:crossplane-gcp-provider@$PROJECT_ID.iam.gserviceaccount.com" --role="roles/editor"
```

4. k8s secret

TODO - don't keep this file locally, add code to download from GSM.
```
kubectl create secret generic gcp-creds -n crossplane-system --from-file=credentials=./crossplane-gcp-provider-key.json
```
5. Configure Provider

```yaml
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-creds
      key: credentials
```

6. Test
